# Generated by Django 4.1.4 on 2023-06-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('e', 'English'), ('r', 'Русский'), ('b', 'Беларуская'), ('f', 'French'), ('o', 'Other language')], help_text='Book language', max_length=1, null=True),
        ),
    ]
